### PR TITLE
Make migration stream more efficient

### PR DESCRIPTION
**Pull request by springmeyer**
While reviewing the migration stream code, I noticed that in the case of v2 tiles we were calling `mapnik.VectorTile.info` twice on the same buffer. This call is not cheap because it:

 - the function is sync and blocks the main event loop, which will slow down the ability of the stream to process concurrently
 - decodes the entire compressed tile (which requires significant memory allocation)
 - iterates over all the layers and features in the vector tile
 - Makes a number of calls to create v8 C++ objects to pass back to JS

This is likely slowing down unpacking of v2 vector tiles in a meaningful way. This PR fixes the problem.

/cc @mapbox/unpacker

### CODE REVIEW

**Comment by mapsam** [comment]
@springmeyer I'd like to bring this along with #107 for the 7.x release. Is this branch still viable?

**Comment by springmeyer** [comment]
@mapsam - just resolved the conflict with master via the github UI - hopefully should be good to review now.

**Comment by mapsam** [comment]
Thanks @springmeyer! I'll work on getting tests passing.

**Comment by springmeyer** [comment]
Thanks @mapsam

**Comment by mapsam** [comment]
@springmeyer I added a sinon spy to the mapnik.VectorTile.info method to assert we are only calling it once per tile. Despite your changes, it looks like `.info` is called twice still - confirmed the same number of calls between master and this branch. Perhaps we're still calling it elsewhere?

**Comment by springmeyer** [comment]
@mapsam - sorry for the delay in responding to this one, and thanks again for helping get this out.

> copy mbtiles with v1 tile logging

The test you are referring to https://github.com/mapbox/mapbox-tile-copy/commit/e0483b62c8eb087fc70c4622a0a84771aa43f430#diff-e9d67ed2ee5f98cf552e2ad8f6190725 looks like it is testing v1 tiles.

It is expected still that `mapnik.VectorTile.info` is called for v1 tiles before and after this PR. What this PR does is ensures only one call for the v2 case (where we don't need to migrate). See https://github.com/mapbox/mapbox-tile-copy/blob/6163db55f50efda1bbdfc07b48b91eda2c0b53c6/lib/migration-stream.js#L60-L85.

So I think we need a tests to ensure it is called only once for v2 tiles. That sound right?

**Comment by mapsam** [comment]
Ah, that makes sense. Thanks @springmeyer - I've updated the test with a valid v2 fixture... what do you think of this? https://github.com/mapbox/mapbox-tile-copy/blob/97db9a261269e5c03e2a514997da567a7f6da906/test/copy.tilelive.test.js#L97-L116

**Comment by mapsam** [comment]
@springmeyer updated so the spy is in the pre-existing v2 tests, plus rearranged the migration stream code to make it a little more readable.

**Comment by springmeyer** [comment]
Great, looks good to merge and roll out when you have time @mapsam - thanks for the help!

**Comment by mapsam** [comment]
🍏  - thanks much @springmeyer for noticing this. Will plan on releasing a new minor version for this.

**Pull request merged**
