### PR TITLE
[TESTING] add ability to write to local filesystem

### PR DESCRIPTION
**Pull request by springmeyer**
I wanted the ability to easily write tiles to the local filesystem for debugging things in upstream modules like https://github.com/mapbox/mapnik-omnivore/pull/172. Queuing this PR up not because I think this needs to land but rather for my future debugging self to be able to easily find this.

### CODE REVIEW

**Comment by mapsam** [comment]
> Get a gut-check

@springmeyer @allieoop @GretaCB 👍 to adding this as feature! Would like to see some tests added (for a valid/invalid filepath).

> Consider if adding mbtiles export support would be better than writing to a file system

I'm 👎 on this idea, mostly because it's the reverse goal of one codepath this module provides (send tiles from an MBTiles to s3/filesystem). Would we be writing code to construct the metadata tables and `json` rows (mapnik omnivore-esque)? I imagine I'm missing some context of why this would be beneficial, though. Wanting to view the tiles with mbview, perhaps?

**Comment by springmeyer** [comment]
> Wanting to view the tiles with mbview, perhaps?

Correct, that was my thinking. Thanks for weighing in. My hesitation is that then this tool would have value and maintenance burden for something its not intentionally designed for. While the pro is that being able to debug easier might make this tool funner to work on and less buggy.

**Comment by allieoop** [comment]
> Consider if adding mbtiles export support would be better than writing to a file system
@springmeyer what do you mean by mbtiles export support? Are you referring to your noop sink idea?

**Comment by springmeyer** [comment]
> @springmeyer what do you mean by mbtiles export support? Are you referring to your noop sink idea?

Adding mbtiles export support would mean being able to do `node bin/mapbox-tile-copy.js local.mbtiles validated-copy.mbtiles` (using https://github.com/mapbox/node-mbtiles). So, being able to take tiles from `local.mbtiles`, running them through the processing, and then outputting to a new `.mbtiles` file. However I no longer think this is worth it because: 1) because of @mapsam's feelings above and 2) the file:// approach works well enough for debugging behavior and 3) for performance testing we've learned about the overhead of writing and so a `noop://` approach feels more useful for change detection for performance.

> Are you referring to your noop sink idea?

Right the `noop` idea is another type of sink idea. The goal would be to use mapbox-tile-copy but without any writing so that we could better understand whether changes to the read functionality have any performance impact, since the `noop` should be very low cost writing.

**Comment by mapsam** [comment]
> Right the noop idea is another type of sink idea.

I wonder if we could, for the sake of making sense of the `noop` idea, flag this as a "dry run" concept used for testing. The CLI allows you to pass in `--dry-run` which means you want to do everything except PUT to s3 to see if it's all working as expected.

**Comment by springmeyer** [comment]
> The CLI allows you to pass in --dry-run which means you want to do everything except PUT to s3 to see if it's all working as expected.

👍 I like this idea. So, if we pass `--dry-run` the `noop` sink would be loaded dynamically

**Comment by springmeyer** [comment]
Added a `noop://` sink target: 
https://github.com/mapbox/mapbox-tile-copy/commit/3618d8f66cc5b7cbce164c3f8461a8d2b5c4d39a. This can now be used to completely avoid any overhead from writing to a `file://` or putting to slow network (`s3://`)  and therefore should allow more easy isolation of performance changes to the read/source side of things.

Next action is to pull https://github.com/mapbox/mapbox-tile-copy/commit/3618d8f66cc5b7cbce164c3f8461a8d2b5c4d39a into https://github.com/mapbox/mapbox-tile-copy/pull/126 and benchmark again to see whether the gzip changes show up more clearly when the `noop://` is used.

**Comment by springmeyer** [comment]
Since this has only been used for testing, going to close this as I won't be planning on merging it.

**Pull request closed without merging**
