### PR TITLE
add note about source-layer

### PR DESCRIPTION
**Pull request by lyzidiamond**
Adds note about `source-layer` to README. cc @rclark @GretaCB @lucaswoj

### CODE REVIEW

**Comment by rclark** [comment]
Hmm now I'm maybe seeing what you meant more about wondering where to put this bit of documentation. Maybe you could provide some links to style docs to help clarify what `style layers` are, since they really don't exist in the context of mapbox-tile-copy itself?

**Comment by lyzidiamond** [comment]
@rclark just added a couple links. what do you think?

**Comment by rclark** [comment]
:+1: thanks!

**Comment by lyzidiamond** [comment]
@rclark can I merge this?

**Comment by rclark** [comment]
hmm @lyzidiamond behavior has changed slightly -- you can specify `--layerName` and this will become the appropriate `source-layer` to provide in your style doc. If you do not specify this parameter, then the default value is the file's name.

**Pull request closed without merging**
